// This file is auto-generated by @hey-api/openapi-ts

import { buildClientParams, type Client, type ClientMeta, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { AccountsAuthGetSessionErrors, AccountsAuthGetSessionResponses, AccountsAuthRequestOtpErrors, AccountsAuthRequestOtpResponses, AccountsAuthSignOutErrors, AccountsAuthSignOutResponses, AccountsAuthVerifyOtpErrors, AccountsAuthVerifyOtpResponses, AccountsGetErrors, AccountsGetResponses, AccountsMarketingGetErrors, AccountsMarketingGetResponses, AccountsMarketingUpdateErrors, AccountsMarketingUpdateResponses, AccountsOrdersGetErrors, AccountsOrdersGetResponses, AccountsOrdersListErrors, AccountsOrdersListResponses, AccountsUpdateErrors, AccountsUpdateResponses, CartAddErrors, CartAddResponses, CartCheckoutErrors, CartCheckoutResponses, CartCountErrors, CartCountResponses, CartGetErrors, CartGetResponses, CartMigrateErrors, CartMigrateResponses, CartRemoveErrors, CartRemoveResponses, CartUpdateErrors, CartUpdateResponses, CollectionsGetCollectionErrors, CollectionsGetCollectionProductsErrors, CollectionsGetCollectionProductsResponses, CollectionsGetCollectionResponses, CollectionsGetCollectionsErrors, CollectionsGetCollectionsResponses, ContentBannerTextErrors, ContentBannerTextResponses, ContentBlockErrors, ContentBlockResponses, ContentBlocksErrors, ContentBlocksResponses, ProductsGetInfiniteProductsErrors, ProductsGetInfiniteProductsResponses, ProductsGetProductErrors, ProductsGetProductResponses, ProductsGetSearchProductsErrors, ProductsGetSearchProductsResponses, ProductsGetTrendingProductsErrors, ProductsGetTrendingProductsResponses, WishlistAddErrors, WishlistAddResponses, WishlistClearErrors, WishlistClearResponses, WishlistGetErrors, WishlistGetResponses, WishlistRemoveErrors, WishlistRemoveResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

class HeyApiClient {
    protected client: Client;
    
    constructor(args?: {
        client?: Client;
    }) {
        this.client = args?.client ?? client;
    }
}

class HeyApiRegistry<T> {
    private readonly defaultKey = 'default';
    
    private readonly instances: Map<string, T> = new Map();
    
    get(key?: string): T {
        const instance = this.instances.get(key ?? this.defaultKey);
        if (!instance) {
            throw new Error(`No SDK client found. Create one with "new PuddleStorefrontApi()" to fix this error.`);
        }
        return instance;
    }
    
    set(value: T, key?: string): void {
        this.instances.set(key ?? this.defaultKey, value);
    }
}

export class PuddleStorefrontApi extends HeyApiClient {
    public static readonly __registry: HeyApiRegistry<PuddleStorefrontApi> = new HeyApiRegistry<PuddleStorefrontApi>();
    
    constructor(args?: {
        client?: Client;
        key?: string;
    }) {
        super(args);
        PuddleStorefrontApi.__registry.set(this, args?.key);
    }
    
    /**
     * Get current customer
     *
     * Retrieves the currently authenticated customer session profile. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable.
     */
    public accountsGet<ThrowOnError extends boolean = false>(parameters: {
        authorization: string;
        'x-puddle-storefront-host'?: string;
    }, options?: Options<never, ThrowOnError>): RequestResult<AccountsGetResponses, AccountsGetErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [{ in: 'headers', key: 'authorization' }, { in: 'headers', key: 'x-puddle-storefront-host' }] }]);
        return (options?.client ?? this.client).get<AccountsGetResponses, AccountsGetErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/account',
            ...options,
            ...params
        });
    }
    
    /**
     * Update customer profile
     *
     * Updates the profile details for the authenticated customer. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable. Requires a valid customer session cookie for the resolved storefront.
     */
    public accountsUpdate<ThrowOnError extends boolean = false>(parameters: {
        authorization: string;
        'x-puddle-storefront-host'?: string;
        firstName: string;
        lastName: string;
        phone?: string;
    }, options?: Options<never, ThrowOnError>): RequestResult<AccountsUpdateResponses, AccountsUpdateErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'headers', key: 'authorization' },
                    { in: 'headers', key: 'x-puddle-storefront-host' },
                    { in: 'body', key: 'firstName' },
                    { in: 'body', key: 'lastName' },
                    { in: 'body', key: 'phone' }
                ] }]);
        return (options?.client ?? this.client).put<AccountsUpdateResponses, AccountsUpdateErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/account',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Get marketing consent
     *
     * Retrieves the marketing consent status for the authenticated customer. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable. Requires a valid customer session cookie for the resolved storefront.
     */
    public accountsMarketingGet<ThrowOnError extends boolean = false>(options?: Options<never, ThrowOnError>): RequestResult<AccountsMarketingGetResponses, AccountsMarketingGetErrors, ThrowOnError> {
        return (options?.client ?? this.client).get<AccountsMarketingGetResponses, AccountsMarketingGetErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/account/marketing',
            ...options
        });
    }
    
    /**
     * Update marketing consent
     *
     * Updates the marketing consent status for the authenticated customer. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable. Requires a valid customer session cookie for the resolved storefront.
     */
    public accountsMarketingUpdate<ThrowOnError extends boolean = false>(parameters: {
        authorization: string;
        'x-puddle-storefront-host'?: string;
        consent: boolean;
    }, options?: Options<never, ThrowOnError>): RequestResult<AccountsMarketingUpdateResponses, AccountsMarketingUpdateErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'headers', key: 'authorization' },
                    { in: 'headers', key: 'x-puddle-storefront-host' },
                    { in: 'body', key: 'consent' }
                ] }]);
        return (options?.client ?? this.client).put<AccountsMarketingUpdateResponses, AccountsMarketingUpdateErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/account/marketing',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * List customer orders
     *
     * Retrieves a list of orders for the authenticated customer. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable. Requires a valid customer session cookie for the resolved storefront.
     */
    public accountsOrdersList<ThrowOnError extends boolean = false>(options?: Options<never, ThrowOnError>): RequestResult<AccountsOrdersListResponses, AccountsOrdersListErrors, ThrowOnError> {
        return (options?.client ?? this.client).get<AccountsOrdersListResponses, AccountsOrdersListErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/account/orders',
            ...options
        });
    }
    
    /**
     * Get order
     *
     * Retrieves details of a specific order for the authenticated customer. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable. Requires a valid customer session cookie for the resolved storefront.
     */
    public accountsOrdersGet<ThrowOnError extends boolean = false>(parameters: {
        authorization: string;
        'x-puddle-storefront-host'?: string;
        orderId: string;
    }, options?: Options<never, ThrowOnError>): RequestResult<AccountsOrdersGetResponses, AccountsOrdersGetErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'headers', key: 'authorization' },
                    { in: 'headers', key: 'x-puddle-storefront-host' },
                    { in: 'path', key: 'orderId' }
                ] }]);
        return (options?.client ?? this.client).get<AccountsOrdersGetResponses, AccountsOrdersGetErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/account/orders/{orderId}',
            ...options,
            ...params
        });
    }
    
    /**
     * Request OTP
     *
     * Requests a one-time password (OTP) for customer authentication. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable.
     */
    public accountsAuthRequestOtp<ThrowOnError extends boolean = false>(parameters: {
        authorization: string;
        'x-puddle-storefront-host'?: string;
        email: string;
    }, options?: Options<never, ThrowOnError>): RequestResult<AccountsAuthRequestOtpResponses, AccountsAuthRequestOtpErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'headers', key: 'authorization' },
                    { in: 'headers', key: 'x-puddle-storefront-host' },
                    { in: 'body', key: 'email' }
                ] }]);
        return (options?.client ?? this.client).post<AccountsAuthRequestOtpResponses, AccountsAuthRequestOtpErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/auth/request-otp',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Verify OTP
     *
     * Verifies the one-time password (OTP) to authenticate the customer. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable.
     */
    public accountsAuthVerifyOtp<ThrowOnError extends boolean = false>(parameters: {
        authorization: string;
        'x-puddle-storefront-host'?: string;
        email: string;
        otp: string;
        firstName?: string;
        lastName?: string;
        phone?: string;
    }, options?: Options<never, ThrowOnError>): RequestResult<AccountsAuthVerifyOtpResponses, AccountsAuthVerifyOtpErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'headers', key: 'authorization' },
                    { in: 'headers', key: 'x-puddle-storefront-host' },
                    { in: 'body', key: 'email' },
                    { in: 'body', key: 'otp' },
                    { in: 'body', key: 'firstName' },
                    { in: 'body', key: 'lastName' },
                    { in: 'body', key: 'phone' }
                ] }]);
        return (options?.client ?? this.client).post<AccountsAuthVerifyOtpResponses, AccountsAuthVerifyOtpErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/auth/verify-otp',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Get session
     *
     * Retrieves the current customer session details. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable.
     */
    public accountsAuthGetSession<ThrowOnError extends boolean = false>(options?: Options<never, ThrowOnError>): RequestResult<AccountsAuthGetSessionResponses, AccountsAuthGetSessionErrors, ThrowOnError> {
        return (options?.client ?? this.client).get<AccountsAuthGetSessionResponses, AccountsAuthGetSessionErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/auth/session',
            ...options
        });
    }
    
    /**
     * Sign out
     *
     * Signs out the currently authenticated customer. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable.
     */
    public accountsAuthSignOut<ThrowOnError extends boolean = false>(options?: Options<never, ThrowOnError>): RequestResult<AccountsAuthSignOutResponses, AccountsAuthSignOutErrors, ThrowOnError> {
        return (options?.client ?? this.client).post<AccountsAuthSignOutResponses, AccountsAuthSignOutErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/auth/sign-out',
            ...options
        });
    }
    
    /**
     * Initialise checkout
     *
     * Initialises checkout for the current cart and returns the checkout session details. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable.
     */
    public cartCheckout<ThrowOnError extends boolean = false>(parameters: {
        authorization: string;
        'x-puddle-storefront-host'?: string;
        couponCode?: string | null;
        giftCardCodes?: Array<string> | null;
        deliveryMethod?: string | null;
        deliveryMethodId?: string | null;
        deliveryMethodCode?: string | null;
    }, options?: Options<never, ThrowOnError>): RequestResult<CartCheckoutResponses, CartCheckoutErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'headers', key: 'authorization' },
                    { in: 'headers', key: 'x-puddle-storefront-host' },
                    { in: 'body', key: 'couponCode' },
                    { in: 'body', key: 'giftCardCodes' },
                    { in: 'body', key: 'deliveryMethod' },
                    { in: 'body', key: 'deliveryMethodId' },
                    { in: 'body', key: 'deliveryMethodCode' }
                ] }]);
        return (options?.client ?? this.client).post<CartCheckoutResponses, CartCheckoutErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/cart/checkout',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Get cart count
     *
     * Retrieves the current number of items in the cart. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable.
     */
    public cartCount<ThrowOnError extends boolean = false>(options?: Options<never, ThrowOnError>): RequestResult<CartCountResponses, CartCountErrors, ThrowOnError> {
        return (options?.client ?? this.client).get<CartCountResponses, CartCountErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/cart/count',
            ...options
        });
    }
    
    /**
     * Migrate cart
     *
     * Migrates a guest cart into the authenticated customer cart when both are present. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable.
     */
    public cartMigrate<ThrowOnError extends boolean = false>(options?: Options<never, ThrowOnError>): RequestResult<CartMigrateResponses, CartMigrateErrors, ThrowOnError> {
        return (options?.client ?? this.client).post<CartMigrateResponses, CartMigrateErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/cart/migrate',
            ...options
        });
    }
    
    /**
     * Get cart
     *
     * Retrieves the current cart contents. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable.
     */
    public cartGet<ThrowOnError extends boolean = false>(options?: Options<never, ThrowOnError>): RequestResult<CartGetResponses, CartGetErrors, ThrowOnError> {
        return (options?.client ?? this.client).get<CartGetResponses, CartGetErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/cart',
            ...options
        });
    }
    
    /**
     * Add cart item
     *
     * Adds a product or product variant to the current cart. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable.
     */
    public cartAdd<ThrowOnError extends boolean = false>(parameters: {
        authorization: string;
        'x-puddle-storefront-host'?: string;
        productId: string;
        productVariantId?: string;
        quantity: number;
        customText?: {
            [key: string]: string;
        };
    }, options?: Options<never, ThrowOnError>): RequestResult<CartAddResponses, CartAddErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'headers', key: 'authorization' },
                    { in: 'headers', key: 'x-puddle-storefront-host' },
                    { in: 'body', key: 'productId' },
                    { in: 'body', key: 'productVariantId' },
                    { in: 'body', key: 'quantity' },
                    { in: 'body', key: 'customText' }
                ] }]);
        return (options?.client ?? this.client).post<CartAddResponses, CartAddErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/cart/items',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Remove cart item
     *
     * Removes a cart item from the current cart. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable.
     */
    public cartRemove<ThrowOnError extends boolean = false>(parameters: {
        authorization: string;
        'x-puddle-storefront-host'?: string;
        cartProductId: string;
    }, options?: Options<never, ThrowOnError>): RequestResult<CartRemoveResponses, CartRemoveErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'headers', key: 'authorization' },
                    { in: 'headers', key: 'x-puddle-storefront-host' },
                    { in: 'path', key: 'cartProductId' }
                ] }]);
        return (options?.client ?? this.client).delete<CartRemoveResponses, CartRemoveErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/cart/items/{cartProductId}',
            ...options,
            ...params
        });
    }
    
    /**
     * Update cart item quantity
     *
     * Updates the quantity of an existing cart item. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable.
     */
    public cartUpdate<ThrowOnError extends boolean = false>(parameters: {
        authorization: string;
        'x-puddle-storefront-host'?: string;
        cartProductId: string;
        quantity: number;
    }, options?: Options<never, ThrowOnError>): RequestResult<CartUpdateResponses, CartUpdateErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'headers', key: 'authorization' },
                    { in: 'headers', key: 'x-puddle-storefront-host' },
                    { in: 'path', key: 'cartProductId' },
                    { in: 'body', key: 'quantity' }
                ] }]);
        return (options?.client ?? this.client).put<CartUpdateResponses, CartUpdateErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/cart/items/{cartProductId}',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Get all collections
     *
     * Retrieves a list of all collections for the storefront. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable.
     */
    public collectionsGetCollections<ThrowOnError extends boolean = false>(parameters: {
        authorization: string;
        'x-puddle-storefront-host'?: string;
        structure?: 'flat' | 'tree';
    }, options?: Options<never, ThrowOnError>): RequestResult<CollectionsGetCollectionsResponses, CollectionsGetCollectionsErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'headers', key: 'authorization' },
                    { in: 'headers', key: 'x-puddle-storefront-host' },
                    { in: 'query', key: 'structure' }
                ] }]);
        return (options?.client ?? this.client).get<CollectionsGetCollectionsResponses, CollectionsGetCollectionsErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/collections',
            ...options,
            ...params
        });
    }
    
    /**
     * Get collection
     *
     * Retrieves a single collection by the slug provided in the request body. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable.
     */
    public collectionsGetCollection<ThrowOnError extends boolean = false>(parameters: {
        authorization: string;
        'x-puddle-storefront-host'?: string;
        slug: string;
        includeChildren?: boolean;
    }, options?: Options<never, ThrowOnError>): RequestResult<CollectionsGetCollectionResponses, CollectionsGetCollectionErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'headers', key: 'authorization' },
                    { in: 'headers', key: 'x-puddle-storefront-host' },
                    { in: 'body', key: 'slug' },
                    { in: 'body', key: 'includeChildren' }
                ] }]);
        return (options?.client ?? this.client).post<CollectionsGetCollectionResponses, CollectionsGetCollectionErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/collection',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Get collection products
     *
     * Retrieves products that belong to the collection identified by the slug in the request body. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable.
     */
    public collectionsGetCollectionProducts<ThrowOnError extends boolean = false>(parameters: {
        authorization: string;
        'x-puddle-storefront-host'?: string;
        slug: string;
        sort?: 'PRICE_ASC' | 'PRICE_DESC' | 'NAME_ASC' | 'NAME_DESC' | 'NEWEST' | 'OLDEST';
    }, options?: Options<never, ThrowOnError>): RequestResult<CollectionsGetCollectionProductsResponses, CollectionsGetCollectionProductsErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'headers', key: 'authorization' },
                    { in: 'headers', key: 'x-puddle-storefront-host' },
                    { in: 'body', key: 'slug' },
                    { in: 'body', key: 'sort' }
                ] }]);
        return (options?.client ?? this.client).post<CollectionsGetCollectionProductsResponses, CollectionsGetCollectionProductsErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/collection/products',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Get search products
     *
     * Retrieves a list of products suitable for search. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable.
     */
    public productsGetSearchProducts<ThrowOnError extends boolean = false>(options?: Options<never, ThrowOnError>): RequestResult<ProductsGetSearchProductsResponses, ProductsGetSearchProductsErrors, ThrowOnError> {
        return (options?.client ?? this.client).get<ProductsGetSearchProductsResponses, ProductsGetSearchProductsErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/products/search',
            ...options
        });
    }
    
    /**
     * Get infinite products
     *
     * Retrieves a paginated list of products for a category, collection, or all. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable.
     */
    public productsGetInfiniteProducts<ThrowOnError extends boolean = false>(parameters: {
        authorization: string;
        'x-puddle-storefront-host'?: string;
        type?: 'COLLECTION' | 'ALL';
        id?: string;
    }, options?: Options<never, ThrowOnError>): RequestResult<ProductsGetInfiniteProductsResponses, ProductsGetInfiniteProductsErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'headers', key: 'authorization' },
                    { in: 'headers', key: 'x-puddle-storefront-host' },
                    { in: 'query', key: 'type' },
                    { in: 'query', key: 'id' }
                ] }]);
        return (options?.client ?? this.client).get<ProductsGetInfiniteProductsResponses, ProductsGetInfiniteProductsErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/products/infinite',
            ...options,
            ...params
        });
    }
    
    /**
     * Get trending products
     *
     * Retrieves a list of trending products. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable.
     */
    public productsGetTrendingProducts<ThrowOnError extends boolean = false>(options?: Options<never, ThrowOnError>): RequestResult<ProductsGetTrendingProductsResponses, ProductsGetTrendingProductsErrors, ThrowOnError> {
        return (options?.client ?? this.client).get<ProductsGetTrendingProductsResponses, ProductsGetTrendingProductsErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/products/trending',
            ...options
        });
    }
    
    /**
     * Get product
     *
     * Retrieves a single product by the slug provided in the request body. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable.
     */
    public productsGetProduct<ThrowOnError extends boolean = false>(parameters: {
        authorization: string;
        'x-puddle-storefront-host'?: string;
        slug: string;
    }, options?: Options<never, ThrowOnError>): RequestResult<ProductsGetProductResponses, ProductsGetProductErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'headers', key: 'authorization' },
                    { in: 'headers', key: 'x-puddle-storefront-host' },
                    { in: 'body', key: 'slug' }
                ] }]);
        return (options?.client ?? this.client).post<ProductsGetProductResponses, ProductsGetProductErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/product',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Get content blocks
     *
     * Retrieves all configured storefront content blocks for the current store. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable.
     */
    public contentBlocks<ThrowOnError extends boolean = false>(options?: Options<never, ThrowOnError>): RequestResult<ContentBlocksResponses, ContentBlocksErrors, ThrowOnError> {
        return (options?.client ?? this.client).get<ContentBlocksResponses, ContentBlocksErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/content/blocks',
            ...options
        });
    }
    
    /**
     * Get content block
     *
     * Retrieves a single storefront content block by its id. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable.
     */
    public contentBlock<ThrowOnError extends boolean = false>(parameters: {
        authorization: string;
        'x-puddle-storefront-host'?: string;
        blockId: string;
    }, options?: Options<never, ThrowOnError>): RequestResult<ContentBlockResponses, ContentBlockErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'headers', key: 'authorization' },
                    { in: 'headers', key: 'x-puddle-storefront-host' },
                    { in: 'path', key: 'blockId' }
                ] }]);
        return (options?.client ?? this.client).get<ContentBlockResponses, ContentBlockErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/content/blocks/{blockId}',
            ...options,
            ...params
        });
    }
    
    /**
     * Get banner text
     *
     * Retrieves the active banner text for the storefront if enabled. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable.
     */
    public contentBannerText<ThrowOnError extends boolean = false>(options?: Options<never, ThrowOnError>): RequestResult<ContentBannerTextResponses, ContentBannerTextErrors, ThrowOnError> {
        return (options?.client ?? this.client).get<ContentBannerTextResponses, ContentBannerTextErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/content/banner-text',
            ...options
        });
    }
    
    /**
     * Get wishlist
     *
     * Retrieves the current wishlist contents. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable.
     */
    public wishlistGet<ThrowOnError extends boolean = false>(options?: Options<never, ThrowOnError>): RequestResult<WishlistGetResponses, WishlistGetErrors, ThrowOnError> {
        return (options?.client ?? this.client).get<WishlistGetResponses, WishlistGetErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/wishlist',
            ...options
        });
    }
    
    /**
     * Clear wishlist
     *
     * Removes all wishlist items from the current wishlist. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable.
     */
    public wishlistClear<ThrowOnError extends boolean = false>(options?: Options<never, ThrowOnError>): RequestResult<WishlistClearResponses, WishlistClearErrors, ThrowOnError> {
        return (options?.client ?? this.client).delete<WishlistClearResponses, WishlistClearErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/wishlist/items',
            ...options
        });
    }
    
    /**
     * Add wishlist item
     *
     * Adds a product or product variant to the current wishlist. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable.
     */
    public wishlistAdd<ThrowOnError extends boolean = false>(parameters: {
        authorization: string;
        'x-puddle-storefront-host'?: string;
        productId: string;
        productVariantId?: string;
    }, options?: Options<never, ThrowOnError>): RequestResult<WishlistAddResponses, WishlistAddErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'headers', key: 'authorization' },
                    { in: 'headers', key: 'x-puddle-storefront-host' },
                    { in: 'body', key: 'productId' },
                    { in: 'body', key: 'productVariantId' }
                ] }]);
        return (options?.client ?? this.client).post<WishlistAddResponses, WishlistAddErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/wishlist/items',
            ...options,
            ...params,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers,
                ...params.headers
            }
        });
    }
    
    /**
     * Remove wishlist item
     *
     * Removes a wishlist item from the current wishlist. Requires `Authorization: Bearer <storefront-public-key>`. Server-side callers must include `x-puddle-storefront-host` when `Origin`/`Referer` is unavailable.
     */
    public wishlistRemove<ThrowOnError extends boolean = false>(parameters: {
        authorization: string;
        'x-puddle-storefront-host'?: string;
        wishlistProductId: string;
    }, options?: Options<never, ThrowOnError>): RequestResult<WishlistRemoveResponses, WishlistRemoveErrors, ThrowOnError> {
        const params = buildClientParams([parameters], [{ args: [
                    { in: 'headers', key: 'authorization' },
                    { in: 'headers', key: 'x-puddle-storefront-host' },
                    { in: 'path', key: 'wishlistProductId' }
                ] }]);
        return (options?.client ?? this.client).delete<WishlistRemoveResponses, WishlistRemoveErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/wishlist/items/{wishlistProductId}',
            ...options,
            ...params
        });
    }
}
