// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.puddle.co.za/storefront/v1' | (string & {});
};

/**
 * The request could not be processed because the input is invalid. error (400)
 *
 * The error information
 */
export type ErrorBadRequest = {
    /**
     * The error message
     */
    message: string;
    /**
     * The error code
     */
    code: string;
    /**
     * An array of issues that were responsible for the error
     */
    issues?: Array<{
        message: string;
    }>;
};

/**
 * The storefront public key is missing or invalid. error (401)
 *
 * The error information
 */
export type ErrorUnauthorized = {
    /**
     * The error message
     */
    message: string;
    /**
     * The error code
     */
    code: string;
    /**
     * An array of issues that were responsible for the error
     */
    issues?: Array<{
        message: string;
    }>;
};

/**
 * The storefront public key, host, or customer session is not allowed to access this resource. error (403)
 *
 * The error information
 */
export type ErrorForbidden = {
    /**
     * The error message
     */
    message: string;
    /**
     * The error code
     */
    code: string;
    /**
     * An array of issues that were responsible for the error
     */
    issues?: Array<{
        message: string;
    }>;
};

/**
 * The requested resource could not be found. error (404)
 *
 * The error information
 */
export type ErrorNotFound = {
    /**
     * The error message
     */
    message: string;
    /**
     * The error code
     */
    code: string;
    /**
     * An array of issues that were responsible for the error
     */
    issues?: Array<{
        message: string;
    }>;
};

/**
 * The request conflicts with the current cart, inventory, or account state. error (409)
 *
 * The error information
 */
export type ErrorConflict = {
    /**
     * The error message
     */
    message: string;
    /**
     * The error code
     */
    code: string;
    /**
     * An array of issues that were responsible for the error
     */
    issues?: Array<{
        message: string;
    }>;
};

/**
 * Too many requests. Retry after a short delay. error (429)
 *
 * The error information
 */
export type ErrorTooManyRequests = {
    /**
     * The error message
     */
    message: string;
    /**
     * The error code
     */
    code: string;
    /**
     * An array of issues that were responsible for the error
     */
    issues?: Array<{
        message: string;
    }>;
};

/**
 * An unexpected server error occurred. error (500)
 *
 * The error information
 */
export type ErrorInternalServerError = {
    /**
     * The error message
     */
    message: string;
    /**
     * The error code
     */
    code: string;
    /**
     * An array of issues that were responsible for the error
     */
    issues?: Array<{
        message: string;
    }>;
};

export type Schema0 = {
    id: string;
    storeId?: string | null;
    name: string;
    description?: string | null;
    slug: string;
    seoTitle?: string | null;
    seoDescription?: string | null;
    type: 'MANUAL' | 'AUTOMATED';
    ruleSet?: Array<{
        field: 'price' | 'tags' | 'status' | 'type' | 'collectionId' | 'createdAt';
        operator: 'eq' | 'ne' | 'lt' | 'lte' | 'gt' | 'gte' | 'contains' | 'in' | 'before' | 'after';
        value: string | number | boolean | Array<string> | Array<number>;
    }> | null;
    imageId: string | null;
    imageUrl?: string | null;
    imageUrlSet?: string | null;
    hidden?: boolean | null;
    children: Array<Schema0>;
};

export type AccountsGetData = {
    body?: never;
    headers: {
        /**
         * Bearer <storefront-public-key>
         */
        authorization: string;
        /**
         * Required for server-side callers when Origin/Referer is unavailable.
         */
        'x-puddle-storefront-host'?: string;
    };
    path?: never;
    query?: never;
    url: '/account';
};

export type AccountsGetErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type AccountsGetError = AccountsGetErrors[keyof AccountsGetErrors];

export type AccountsGetResponses = {
    /**
     * Successful response
     */
    200: {
        id: string;
        email: string;
        firstName: string;
        lastName: string;
        phone?: string | null;
    } | null;
};

export type AccountsGetResponse = AccountsGetResponses[keyof AccountsGetResponses];

export type AccountsUpdateData = {
    body: {
        firstName: string;
        lastName: string;
        phone?: string;
    };
    headers: {
        /**
         * Bearer <storefront-public-key>
         */
        authorization: string;
        /**
         * Required for server-side callers when Origin/Referer is unavailable.
         */
        'x-puddle-storefront-host'?: string;
    };
    path?: never;
    query?: never;
    url: '/account';
};

export type AccountsUpdateErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type AccountsUpdateError = AccountsUpdateErrors[keyof AccountsUpdateErrors];

export type AccountsUpdateResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type AccountsMarketingGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account/marketing';
};

export type AccountsMarketingGetErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type AccountsMarketingGetError = AccountsMarketingGetErrors[keyof AccountsMarketingGetErrors];

export type AccountsMarketingGetResponses = {
    /**
     * Successful response
     */
    200: {
        consent: boolean;
    };
};

export type AccountsMarketingGetResponse = AccountsMarketingGetResponses[keyof AccountsMarketingGetResponses];

export type AccountsMarketingUpdateData = {
    body: {
        consent: boolean;
    };
    headers: {
        /**
         * Bearer <storefront-public-key>
         */
        authorization: string;
        /**
         * Required for server-side callers when Origin/Referer is unavailable.
         */
        'x-puddle-storefront-host'?: string;
    };
    path?: never;
    query?: never;
    url: '/account/marketing';
};

export type AccountsMarketingUpdateErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type AccountsMarketingUpdateError = AccountsMarketingUpdateErrors[keyof AccountsMarketingUpdateErrors];

export type AccountsMarketingUpdateResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type AccountsMarketingUpdateResponse = AccountsMarketingUpdateResponses[keyof AccountsMarketingUpdateResponses];

export type AccountsOrdersListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/account/orders';
};

export type AccountsOrdersListErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type AccountsOrdersListError = AccountsOrdersListErrors[keyof AccountsOrdersListErrors];

export type AccountsOrdersListResponses = {
    /**
     * Successful response
     */
    200: Array<{
        id: string;
        shortId: string;
        status: 'PENDING' | 'PROCESSING' | 'AWAITING_SHIPMENT' | 'AWAITING_COLLECTION' | 'COLLECTED' | 'SHIPPED' | 'DELIVERED' | 'CANCELLED' | null;
        placedAt: string | null;
        total: number;
        subtotal: number;
        discount: number;
        shipping: number;
        products: Array<{
            id: string;
            product: {
                id: string;
                name: string;
                primaryImageId: string | null;
                primaryImageUrl?: string | null;
                primaryImageSrcSet?: string | null;
                type: string;
                digitalFileUrl?: string | null;
                trackInventory: boolean | null;
            };
            productVariant: {
                id: string | null;
                imageId: string | null;
                imageUrl?: string | null;
                imageUrlSet?: string | null;
                attributes: {
                    [key: string]: string;
                } | null;
            };
            status?: string;
            discount: number;
            saleId?: string | null;
            quantity: number;
            price: number;
            customText?: {
                [key: string]: string;
            } | null;
        }>;
        currency?: string | null;
        couponCode?: string | null;
        giftCardId?: string | null;
        giftCardUsage?: number;
        giftCardApplications?: Array<{
            giftCardId: string;
            code: string;
            amount: number;
        }>;
        paymentStatus?: 'AWAITING_PAYMENT' | 'PAID' | 'PARTIALLY_PAID' | 'REFUNDED' | 'PARTIALLY_REFUNDED';
        paymentProvider?: 'PAYSTACK' | null;
        paymentCapturedAmount?: number;
        refundedAmount?: number;
    }>;
};

export type AccountsOrdersListResponse = AccountsOrdersListResponses[keyof AccountsOrdersListResponses];

export type AccountsOrdersGetData = {
    body?: never;
    headers: {
        /**
         * Bearer <storefront-public-key>
         */
        authorization: string;
        /**
         * Required for server-side callers when Origin/Referer is unavailable.
         */
        'x-puddle-storefront-host'?: string;
    };
    path: {
        orderId: string;
    };
    query?: never;
    url: '/account/orders/{orderId}';
};

export type AccountsOrdersGetErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type AccountsOrdersGetError = AccountsOrdersGetErrors[keyof AccountsOrdersGetErrors];

export type AccountsOrdersGetResponses = {
    /**
     * Successful response
     */
    200: {
        id: string;
        shortId: string;
        status: 'PENDING' | 'PROCESSING' | 'AWAITING_SHIPMENT' | 'AWAITING_COLLECTION' | 'COLLECTED' | 'SHIPPED' | 'DELIVERED' | 'CANCELLED' | null;
        placedAt: string | null;
        total: number;
        subtotal: number;
        discount: number;
        shipping: number;
        products: Array<{
            id: string;
            product: {
                id: string;
                name: string;
                primaryImageId: string | null;
                primaryImageUrl?: string | null;
                primaryImageSrcSet?: string | null;
                type: string;
                digitalFileUrl?: string | null;
                trackInventory: boolean | null;
            };
            productVariant: {
                id: string | null;
                imageId: string | null;
                imageUrl?: string | null;
                imageUrlSet?: string | null;
                attributes: {
                    [key: string]: string;
                } | null;
            };
            status?: string;
            discount: number;
            saleId?: string | null;
            quantity: number;
            price: number;
            customText?: {
                [key: string]: string;
            } | null;
        }>;
        currency?: string | null;
        couponCode?: string | null;
        giftCardId?: string | null;
        giftCardUsage?: number;
        giftCardApplications?: Array<{
            giftCardId: string;
            code: string;
            amount: number;
        }>;
        paymentStatus?: 'AWAITING_PAYMENT' | 'PAID' | 'PARTIALLY_PAID' | 'REFUNDED' | 'PARTIALLY_REFUNDED';
        paymentProvider?: 'PAYSTACK' | null;
        paymentCapturedAmount?: number;
        refundedAmount?: number;
        customerId: string | null;
        customerFirstName: string;
        customerLastName: string;
        customerEmail: string;
        customerNotes?: string | null;
        adminNotes?: string | null;
        paymentSummary?: {
            provider: 'PAYSTACK' | null;
            status: 'AWAITING_PAYMENT' | 'PAID' | 'PARTIALLY_PAID' | 'REFUNDED' | 'PARTIALLY_REFUNDED';
            capturedAmount: number;
            refundedAmount: number;
            refundableAmount: number;
        };
        refundHistory?: Array<{
            id: string;
            provider: 'PAYSTACK';
            status: 'PENDING' | 'SUCCEEDED' | 'FAILED' | 'REQUIRES_MANUAL_ACTION';
            amount: number;
            shippingAmount: number;
            reason?: string | null;
            providerRefundId?: string | null;
            failureCode?: string | null;
            failureMessage?: string | null;
            lineItems: Array<{
                orderProductId: string;
                quantity: number;
                amount: number;
            }>;
            requestedByAdminId?: string | null;
            requestedByAdminName?: string | null;
            createdAt: string;
            updatedAt: string;
        }>;
        deliveryMethod: string;
        deliveryMethodId?: string | null;
        deliveryMethodCode?: string | null;
        deliveryMethodSnapshot?: {
            id: string;
            code: string;
            type: string;
            name: string;
            description?: string | null;
            iconKey: string;
            notificationCard?: {
                enabled?: boolean;
                title: string;
                description?: string | null;
                ctaLabel?: string | null;
                ctaHref?: string | null;
            } | null;
        } | null;
        deliveryMethodPayload?: {
            [key: string]: unknown;
        } | null;
        deliveryAddress: {
            recipientName: string;
            recipientPhone: string;
            company?: string;
            streetAddress: string;
            localArea: string;
            city: string;
            postalCode: string;
            zone: string;
            country: string;
            lat?: number;
            lng?: number;
        } | null;
        billingAddress?: {
            recipientName: string;
            recipientPhone: string;
            company?: string;
            streetAddress: string;
            localArea: string;
            city: string;
            postalCode: string;
            zone: string;
            country: string;
            lat?: number;
            lng?: number;
        } | null;
        deliveryInstructions?: string | null;
        deliveryCarrier?: string | null;
        deliveryTrackingId?: string | null;
        deliveryTrackingReference?: string | null;
    };
};

export type AccountsOrdersGetResponse = AccountsOrdersGetResponses[keyof AccountsOrdersGetResponses];

export type AccountsAuthRequestOtpData = {
    body: {
        email: string;
    };
    headers: {
        /**
         * Bearer <storefront-public-key>
         */
        authorization: string;
        /**
         * Required for server-side callers when Origin/Referer is unavailable.
         */
        'x-puddle-storefront-host'?: string;
    };
    path?: never;
    query?: never;
    url: '/auth/request-otp';
};

export type AccountsAuthRequestOtpErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type AccountsAuthRequestOtpError = AccountsAuthRequestOtpErrors[keyof AccountsAuthRequestOtpErrors];

export type AccountsAuthRequestOtpResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type AccountsAuthRequestOtpResponse = AccountsAuthRequestOtpResponses[keyof AccountsAuthRequestOtpResponses];

export type AccountsAuthVerifyOtpData = {
    body: {
        email: string;
        otp: string;
        firstName?: string;
        lastName?: string;
        phone?: string;
    };
    headers: {
        /**
         * Bearer <storefront-public-key>
         */
        authorization: string;
        /**
         * Required for server-side callers when Origin/Referer is unavailable.
         */
        'x-puddle-storefront-host'?: string;
    };
    path?: never;
    query?: never;
    url: '/auth/verify-otp';
};

export type AccountsAuthVerifyOtpErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type AccountsAuthVerifyOtpError = AccountsAuthVerifyOtpErrors[keyof AccountsAuthVerifyOtpErrors];

export type AccountsAuthVerifyOtpResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
        session: {
            session: {
                id: string;
                storeId: string;
                customerId: string;
                expiresAt: string;
            };
            user: {
                id: string;
                email: string;
                firstName: string | null;
                lastName: string | null;
                phone: string | null;
                storeId: string;
            };
        };
    };
};

export type AccountsAuthVerifyOtpResponse = AccountsAuthVerifyOtpResponses[keyof AccountsAuthVerifyOtpResponses];

export type AccountsAuthGetSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/session';
};

export type AccountsAuthGetSessionErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type AccountsAuthGetSessionError = AccountsAuthGetSessionErrors[keyof AccountsAuthGetSessionErrors];

export type AccountsAuthGetSessionResponses = {
    /**
     * Successful response
     */
    200: {
        session: {
            session: {
                id: string;
                storeId: string;
                customerId: string;
                expiresAt: string;
            };
            user: {
                id: string;
                email: string;
                firstName: string | null;
                lastName: string | null;
                phone: string | null;
                storeId: string;
            };
        } | null;
    };
};

export type AccountsAuthGetSessionResponse = AccountsAuthGetSessionResponses[keyof AccountsAuthGetSessionResponses];

export type AccountsAuthSignOutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/sign-out';
};

export type AccountsAuthSignOutErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type AccountsAuthSignOutError = AccountsAuthSignOutErrors[keyof AccountsAuthSignOutErrors];

export type AccountsAuthSignOutResponses = {
    /**
     * Successful response
     */
    200: {
        success: boolean;
    };
};

export type AccountsAuthSignOutResponse = AccountsAuthSignOutResponses[keyof AccountsAuthSignOutResponses];

export type CartCheckoutData = {
    body: {
        couponCode?: string | null;
        giftCardCodes?: Array<string> | null;
        deliveryMethod?: string | null;
        deliveryMethodId?: string | null;
        deliveryMethodCode?: string | null;
    };
    headers: {
        /**
         * Bearer <storefront-public-key>
         */
        authorization: string;
        /**
         * Required for server-side callers when Origin/Referer is unavailable.
         */
        'x-puddle-storefront-host'?: string;
    };
    path?: never;
    query?: never;
    url: '/cart/checkout';
};

export type CartCheckoutErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type CartCheckoutError = CartCheckoutErrors[keyof CartCheckoutErrors];

export type CartCheckoutResponses = {
    /**
     * Successful response
     */
    200: {
        checkoutUrl: string;
        checkoutSessionId: string;
        expiresAt?: string | null;
    };
};

export type CartCheckoutResponse = CartCheckoutResponses[keyof CartCheckoutResponses];

export type CartCountData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cart/count';
};

export type CartCountErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type CartCountError = CartCountErrors[keyof CartCountErrors];

export type CartCountResponses = {
    /**
     * Successful response
     */
    200: number;
};

export type CartCountResponse = CartCountResponses[keyof CartCountResponses];

export type CartMigrateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cart/migrate';
};

export type CartMigrateErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type CartMigrateError = CartMigrateErrors[keyof CartMigrateErrors];

export type CartMigrateResponses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type CartGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cart';
};

export type CartGetErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type CartGetError = CartGetErrors[keyof CartGetErrors];

export type CartGetResponses = {
    /**
     * Successful response
     */
    200: {
        items: Array<{
            id: string;
            product: {
                id: string;
                name: string;
                primaryImageId: string | null;
                primaryImageUrl?: string | null;
                primaryImageSrcSet?: string | null;
                type: 'physical' | 'digital' | 'gift_card';
                trackInventory?: boolean | null;
            };
            productVariant?: {
                id: string;
                imageId?: string | null;
                imageUrl?: string | null;
                imageUrlSet?: string | null;
                attributes: {
                    [key: string]: string;
                };
            } | null;
            discount: number;
            saleId?: string | null;
            quantity: number;
            price: number;
            stockCount?: number | null;
            customText?: {
                [key: string]: string;
            } | null;
        }>;
        errors: Array<{
            cartProductId: string;
            message: string;
        }>;
        warnings: Array<{
            cartProductId: string;
            message: string;
        }>;
        /**
         * Cart merchandise subtotal before discounts, in minor currency units.
         */
        subtotal: number;
        /**
         * Total active sale discount applied to cart items, in minor currency units.
         */
        discount: number;
        /**
         * Cart merchandise total after discounts and before shipping or gift-card payment.
         */
        total: number;
        /**
         * Lowest active free-shipping threshold across enabled delivery methods.
         */
        freeShippingThreshold: number | null;
        /**
         * Amount remaining before the cart reaches the free-shipping threshold.
         */
        amountToFreeShipping: number | null;
    };
};

export type CartGetResponse = CartGetResponses[keyof CartGetResponses];

export type CartAddData = {
    body: {
        productId: string;
        productVariantId?: string;
        quantity: number;
        customText?: {
            [key: string]: string;
        };
    };
    headers: {
        /**
         * Bearer <storefront-public-key>
         */
        authorization: string;
        /**
         * Required for server-side callers when Origin/Referer is unavailable.
         */
        'x-puddle-storefront-host'?: string;
    };
    path?: never;
    query?: never;
    url: '/cart/items';
};

export type CartAddErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type CartAddError = CartAddErrors[keyof CartAddErrors];

export type CartAddResponses = {
    /**
     * Successful response
     */
    200: {
        items: Array<{
            id: string;
            product: {
                id: string;
                name: string;
                primaryImageId: string | null;
                primaryImageUrl?: string | null;
                primaryImageSrcSet?: string | null;
                type: 'physical' | 'digital' | 'gift_card';
                trackInventory?: boolean | null;
            };
            productVariant?: {
                id: string;
                imageId?: string | null;
                imageUrl?: string | null;
                imageUrlSet?: string | null;
                attributes: {
                    [key: string]: string;
                };
            } | null;
            discount: number;
            saleId?: string | null;
            quantity: number;
            price: number;
            stockCount?: number | null;
            customText?: {
                [key: string]: string;
            } | null;
        }>;
        errors: Array<{
            cartProductId: string;
            message: string;
        }>;
        warnings: Array<{
            cartProductId: string;
            message: string;
        }>;
        /**
         * Cart merchandise subtotal before discounts, in minor currency units.
         */
        subtotal: number;
        /**
         * Total active sale discount applied to cart items, in minor currency units.
         */
        discount: number;
        /**
         * Cart merchandise total after discounts and before shipping or gift-card payment.
         */
        total: number;
        /**
         * Lowest active free-shipping threshold across enabled delivery methods.
         */
        freeShippingThreshold: number | null;
        /**
         * Amount remaining before the cart reaches the free-shipping threshold.
         */
        amountToFreeShipping: number | null;
    };
};

export type CartAddResponse = CartAddResponses[keyof CartAddResponses];

export type CartRemoveData = {
    body?: never;
    headers: {
        /**
         * Bearer <storefront-public-key>
         */
        authorization: string;
        /**
         * Required for server-side callers when Origin/Referer is unavailable.
         */
        'x-puddle-storefront-host'?: string;
    };
    path: {
        cartProductId: string;
    };
    query?: never;
    url: '/cart/items/{cartProductId}';
};

export type CartRemoveErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type CartRemoveError = CartRemoveErrors[keyof CartRemoveErrors];

export type CartRemoveResponses = {
    /**
     * Successful response
     */
    200: {
        items: Array<{
            id: string;
            product: {
                id: string;
                name: string;
                primaryImageId: string | null;
                primaryImageUrl?: string | null;
                primaryImageSrcSet?: string | null;
                type: 'physical' | 'digital' | 'gift_card';
                trackInventory?: boolean | null;
            };
            productVariant?: {
                id: string;
                imageId?: string | null;
                imageUrl?: string | null;
                imageUrlSet?: string | null;
                attributes: {
                    [key: string]: string;
                };
            } | null;
            discount: number;
            saleId?: string | null;
            quantity: number;
            price: number;
            stockCount?: number | null;
            customText?: {
                [key: string]: string;
            } | null;
        }>;
        errors: Array<{
            cartProductId: string;
            message: string;
        }>;
        warnings: Array<{
            cartProductId: string;
            message: string;
        }>;
        /**
         * Cart merchandise subtotal before discounts, in minor currency units.
         */
        subtotal: number;
        /**
         * Total active sale discount applied to cart items, in minor currency units.
         */
        discount: number;
        /**
         * Cart merchandise total after discounts and before shipping or gift-card payment.
         */
        total: number;
        /**
         * Lowest active free-shipping threshold across enabled delivery methods.
         */
        freeShippingThreshold: number | null;
        /**
         * Amount remaining before the cart reaches the free-shipping threshold.
         */
        amountToFreeShipping: number | null;
    };
};

export type CartRemoveResponse = CartRemoveResponses[keyof CartRemoveResponses];

export type CartUpdateData = {
    body: {
        quantity: number;
    };
    headers: {
        /**
         * Bearer <storefront-public-key>
         */
        authorization: string;
        /**
         * Required for server-side callers when Origin/Referer is unavailable.
         */
        'x-puddle-storefront-host'?: string;
    };
    path: {
        cartProductId: string;
    };
    query?: never;
    url: '/cart/items/{cartProductId}';
};

export type CartUpdateErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type CartUpdateError = CartUpdateErrors[keyof CartUpdateErrors];

export type CartUpdateResponses = {
    /**
     * Successful response
     */
    200: {
        items: Array<{
            id: string;
            product: {
                id: string;
                name: string;
                primaryImageId: string | null;
                primaryImageUrl?: string | null;
                primaryImageSrcSet?: string | null;
                type: 'physical' | 'digital' | 'gift_card';
                trackInventory?: boolean | null;
            };
            productVariant?: {
                id: string;
                imageId?: string | null;
                imageUrl?: string | null;
                imageUrlSet?: string | null;
                attributes: {
                    [key: string]: string;
                };
            } | null;
            discount: number;
            saleId?: string | null;
            quantity: number;
            price: number;
            stockCount?: number | null;
            customText?: {
                [key: string]: string;
            } | null;
        }>;
        errors: Array<{
            cartProductId: string;
            message: string;
        }>;
        warnings: Array<{
            cartProductId: string;
            message: string;
        }>;
        /**
         * Cart merchandise subtotal before discounts, in minor currency units.
         */
        subtotal: number;
        /**
         * Total active sale discount applied to cart items, in minor currency units.
         */
        discount: number;
        /**
         * Cart merchandise total after discounts and before shipping or gift-card payment.
         */
        total: number;
        /**
         * Lowest active free-shipping threshold across enabled delivery methods.
         */
        freeShippingThreshold: number | null;
        /**
         * Amount remaining before the cart reaches the free-shipping threshold.
         */
        amountToFreeShipping: number | null;
    };
};

export type CartUpdateResponse = CartUpdateResponses[keyof CartUpdateResponses];

export type CollectionsGetCollectionsData = {
    body?: never;
    headers: {
        /**
         * Bearer <storefront-public-key>
         */
        authorization: string;
        /**
         * Required for server-side callers when Origin/Referer is unavailable.
         */
        'x-puddle-storefront-host'?: string;
    };
    path?: never;
    query?: {
        structure?: 'flat' | 'tree';
    };
    url: '/collections';
};

export type CollectionsGetCollectionsErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type CollectionsGetCollectionsError = CollectionsGetCollectionsErrors[keyof CollectionsGetCollectionsErrors];

export type CollectionsGetCollectionsResponses = {
    /**
     * Successful response
     */
    200: Array<{
        id: string;
        storeId?: string | null;
        name: string;
        description?: string | null;
        slug: string;
        seoTitle?: string | null;
        seoDescription?: string | null;
        type: 'MANUAL' | 'AUTOMATED';
        ruleSet?: Array<{
            field: 'price' | 'tags' | 'status' | 'type' | 'collectionId' | 'createdAt';
            operator: 'eq' | 'ne' | 'lt' | 'lte' | 'gt' | 'gte' | 'contains' | 'in' | 'before' | 'after';
            value: string | number | boolean | Array<string> | Array<number>;
        }> | null;
        imageId: string | null;
        imageUrl?: string | null;
        imageUrlSet?: string | null;
        hidden?: boolean | null;
    }> | Array<Schema0>;
};

export type CollectionsGetCollectionsResponse = CollectionsGetCollectionsResponses[keyof CollectionsGetCollectionsResponses];

export type CollectionsGetCollectionData = {
    body: {
        slug: string;
        includeChildren?: boolean;
    };
    headers: {
        /**
         * Bearer <storefront-public-key>
         */
        authorization: string;
        /**
         * Required for server-side callers when Origin/Referer is unavailable.
         */
        'x-puddle-storefront-host'?: string;
    };
    path?: never;
    query?: never;
    url: '/collection';
};

export type CollectionsGetCollectionErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type CollectionsGetCollectionError = CollectionsGetCollectionErrors[keyof CollectionsGetCollectionErrors];

export type CollectionsGetCollectionResponses = {
    /**
     * Successful response
     */
    200: {
        id: string;
        storeId?: string | null;
        name: string;
        description?: string | null;
        slug: string;
        seoTitle?: string | null;
        seoDescription?: string | null;
        type: 'MANUAL' | 'AUTOMATED';
        ruleSet?: Array<{
            field: 'price' | 'tags' | 'status' | 'type' | 'collectionId' | 'createdAt';
            operator: 'eq' | 'ne' | 'lt' | 'lte' | 'gt' | 'gte' | 'contains' | 'in' | 'before' | 'after';
            value: string | number | boolean | Array<string> | Array<number>;
        }> | null;
        imageId: string | null;
        imageUrl?: string | null;
        imageUrlSet?: string | null;
        hidden?: boolean | null;
    } | null;
};

export type CollectionsGetCollectionResponse = CollectionsGetCollectionResponses[keyof CollectionsGetCollectionResponses];

export type CollectionsGetCollectionProductsData = {
    body: {
        slug: string;
        sort?: 'PRICE_ASC' | 'PRICE_DESC' | 'NAME_ASC' | 'NAME_DESC' | 'NEWEST' | 'OLDEST';
    };
    headers: {
        /**
         * Bearer <storefront-public-key>
         */
        authorization: string;
        /**
         * Required for server-side callers when Origin/Referer is unavailable.
         */
        'x-puddle-storefront-host'?: string;
    };
    path?: never;
    query?: never;
    url: '/collection/products';
};

export type CollectionsGetCollectionProductsErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type CollectionsGetCollectionProductsError = CollectionsGetCollectionProductsErrors[keyof CollectionsGetCollectionProductsErrors];

export type CollectionsGetCollectionProductsResponses = {
    /**
     * Successful response
     */
    200: Array<{
        id: string;
        name: string;
        slug: string;
        storeId?: string | null;
        primaryImageId?: string | null;
        primaryImageUrl?: string | null;
        primaryImageSrcSet?: string | null;
        /**
         * Base product price in minor currency units.
         */
        price: number;
        productType: 'physical' | 'digital' | 'gift_card';
        trackInventory: boolean;
        createdAt: string | null;
        updatedAt: string | null;
        stockStatus: 'IN_STOCK' | 'LOW_STOCK' | 'VERY_LOW_STOCK' | 'OUT_OF_STOCK' | 'NOT_TRACKED';
        sales: Array<{
            id?: string;
            /**
             * Calculated discount amount in minor currency units.
             */
            discount: number;
            /**
             * ISO 8601 date-time string. tRPC callers may receive a Date.
             */
            starts: string;
            /**
             * ISO 8601 date-time string. tRPC callers may receive a Date.
             */
            ends: string;
        }> | null;
        hasVariablePrices?: boolean;
    }>;
};

export type CollectionsGetCollectionProductsResponse = CollectionsGetCollectionProductsResponses[keyof CollectionsGetCollectionProductsResponses];

export type ProductsGetSearchProductsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/products/search';
};

export type ProductsGetSearchProductsErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type ProductsGetSearchProductsError = ProductsGetSearchProductsErrors[keyof ProductsGetSearchProductsErrors];

export type ProductsGetSearchProductsResponses = {
    /**
     * Successful response
     */
    200: Array<{
        id: string;
        name: string;
        slug: string;
        storeId?: string | null;
        primaryImageId?: string | null;
        primaryImageUrl?: string | null;
        primaryImageSrcSet?: string | null;
    }>;
};

export type ProductsGetSearchProductsResponse = ProductsGetSearchProductsResponses[keyof ProductsGetSearchProductsResponses];

export type ProductsGetInfiniteProductsData = {
    body?: never;
    headers: {
        /**
         * Bearer <storefront-public-key>
         */
        authorization: string;
        /**
         * Required for server-side callers when Origin/Referer is unavailable.
         */
        'x-puddle-storefront-host'?: string;
    };
    path?: never;
    query?: {
        type?: 'COLLECTION' | 'ALL';
        id?: string;
    };
    url: '/products/infinite';
};

export type ProductsGetInfiniteProductsErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type ProductsGetInfiniteProductsError = ProductsGetInfiniteProductsErrors[keyof ProductsGetInfiniteProductsErrors];

export type ProductsGetInfiniteProductsResponses = {
    /**
     * Successful response
     */
    200: Array<{
        id: string;
        name: string;
        slug: string;
        storeId?: string | null;
        primaryImageId?: string | null;
        primaryImageUrl?: string | null;
        primaryImageSrcSet?: string | null;
        /**
         * Base product price in minor currency units.
         */
        price: number;
        productType: 'physical' | 'digital' | 'gift_card';
        trackInventory: boolean;
        createdAt: string | null;
        updatedAt: string | null;
        stockStatus: 'IN_STOCK' | 'LOW_STOCK' | 'VERY_LOW_STOCK' | 'OUT_OF_STOCK' | 'NOT_TRACKED';
        sales: Array<{
            id?: string;
            /**
             * Calculated discount amount in minor currency units.
             */
            discount: number;
            /**
             * ISO 8601 date-time string. tRPC callers may receive a Date.
             */
            starts: string;
            /**
             * ISO 8601 date-time string. tRPC callers may receive a Date.
             */
            ends: string;
        }> | null;
        hasVariablePrices?: boolean;
    }>;
};

export type ProductsGetInfiniteProductsResponse = ProductsGetInfiniteProductsResponses[keyof ProductsGetInfiniteProductsResponses];

export type ProductsGetTrendingProductsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/products/trending';
};

export type ProductsGetTrendingProductsErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type ProductsGetTrendingProductsError = ProductsGetTrendingProductsErrors[keyof ProductsGetTrendingProductsErrors];

export type ProductsGetTrendingProductsResponses = {
    /**
     * Successful response
     */
    200: Array<{
        id: string;
        name: string;
        slug: string;
        storeId?: string | null;
        primaryImageId?: string | null;
        primaryImageUrl?: string | null;
        primaryImageSrcSet?: string | null;
        /**
         * Base product price in minor currency units.
         */
        price: number;
        productType: 'physical' | 'digital' | 'gift_card';
        trackInventory: boolean;
        createdAt: string | null;
        updatedAt: string | null;
        stockStatus: 'IN_STOCK' | 'LOW_STOCK' | 'VERY_LOW_STOCK' | 'OUT_OF_STOCK' | 'NOT_TRACKED';
        sales: Array<{
            id?: string;
            /**
             * Calculated discount amount in minor currency units.
             */
            discount: number;
            /**
             * ISO 8601 date-time string. tRPC callers may receive a Date.
             */
            starts: string;
            /**
             * ISO 8601 date-time string. tRPC callers may receive a Date.
             */
            ends: string;
        }> | null;
        hasVariablePrices?: boolean;
    }>;
};

export type ProductsGetTrendingProductsResponse = ProductsGetTrendingProductsResponses[keyof ProductsGetTrendingProductsResponses];

export type ProductsGetProductData = {
    body: {
        slug: string;
    };
    headers: {
        /**
         * Bearer <storefront-public-key>
         */
        authorization: string;
        /**
         * Required for server-side callers when Origin/Referer is unavailable.
         */
        'x-puddle-storefront-host'?: string;
    };
    path?: never;
    query?: never;
    url: '/product';
};

export type ProductsGetProductErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type ProductsGetProductError = ProductsGetProductErrors[keyof ProductsGetProductErrors];

export type ProductsGetProductResponses = {
    /**
     * Successful response
     */
    200: {
        id: string;
        name: string;
        slug: string;
        storeId?: string | null;
        primaryImageId?: string | null;
        primaryImageUrl?: string | null;
        primaryImageSrcSet?: string | null;
        description?: string | null;
        status?: 'ACTIVE' | 'DRAFT' | 'ARCHIVED' | null;
        options?: {
            giftCard?: {
                price: {
                    min: number;
                    max: number;
                    options: Array<number>;
                    customAmountEnabled: boolean;
                };
                validityDays: number;
                terms: string;
                recipient: {
                    name: boolean;
                    email: boolean;
                    message: boolean;
                } | null;
            } | null;
        } | null;
        type: 'physical' | 'digital' | 'gift_card';
        /**
         * Base product price in minor currency units.
         */
        price: number;
        stockStatus?: 'IN_STOCK' | 'LOW_STOCK' | 'VERY_LOW_STOCK' | 'OUT_OF_STOCK' | 'NOT_TRACKED';
        stockCount: number;
        trackInventory: boolean;
        customTextFields?: Array<{
            id: string;
            label: string;
            placeholder?: string;
            required?: boolean;
            maxLength?: number;
        }> | null;
        imageIds: Array<string>;
        imageUrls?: Array<string>;
        imageSrcSets?: Array<string>;
        variants: Array<{
            id: string;
            productId: string;
            storeId?: string | null;
            stockCount?: number | null;
            trackInventory?: boolean | null;
            /**
             * Variant-specific price in minor currency units. When null, use the product price.
             */
            price?: number | null;
            imageId?: string | null;
            imageUrl?: string | null;
            imageUrlSet?: string | null;
            attributes: Array<{
                /**
                 * Product option id.
                 */
                id: string;
                /**
                 * Product option name, for example Size or Colour.
                 */
                name: string;
                value: {
                    /**
                     * Product option value id.
                     */
                    id: string;
                    /**
                     * Selected value for this variant option.
                     */
                    value: string;
                };
            }>;
        }>;
        sale?: {
            id: string;
            /**
             * Calculated discount amount in minor currency units.
             */
            discount: number;
            starts: string | null;
            ends: string | null;
            name: string;
            amount: number | null;
            percentage: number | null;
            active: boolean;
            productIds?: Array<string> | null;
            collectionIds?: Array<string> | null;
        };
    } | null;
};

export type ProductsGetProductResponse = ProductsGetProductResponses[keyof ProductsGetProductResponses];

export type ContentBlocksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/content/blocks';
};

export type ContentBlocksErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type ContentBlocksError = ContentBlocksErrors[keyof ContentBlocksErrors];

export type ContentBlocksResponses = {
    /**
     * Successful response
     */
    200: Array<{
        id: string;
        label: string;
        description?: string | null;
        mode: 'single' | 'list';
        fieldSchema: Array<{
            id: string;
            label: string;
            description?: string | null;
            type: 'text' | 'textarea' | 'number' | 'select' | 'boolean' | 'image';
            required: boolean;
            options: Array<{
                label: string;
                value: string;
            }>;
        }>;
        items: Array<{
            entryKey: string;
            [key: string]: string | number | boolean | null | {
                imageId: string | null;
                imageUrl: string | null;
                imageUrls?: {
                    original: string;
                    small: string;
                    medium: string;
                    large: string;
                    thumbnail: string;
                } | null;
                imageSrcSet?: string | null;
            } | string;
        }>;
    }>;
};

export type ContentBlocksResponse = ContentBlocksResponses[keyof ContentBlocksResponses];

export type ContentBlockData = {
    body?: never;
    headers: {
        /**
         * Bearer <storefront-public-key>
         */
        authorization: string;
        /**
         * Required for server-side callers when Origin/Referer is unavailable.
         */
        'x-puddle-storefront-host'?: string;
    };
    path: {
        blockId: string;
    };
    query?: never;
    url: '/content/blocks/{blockId}';
};

export type ContentBlockErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type ContentBlockError = ContentBlockErrors[keyof ContentBlockErrors];

export type ContentBlockResponses = {
    /**
     * Successful response
     */
    200: {
        id: string;
        label: string;
        description?: string | null;
        mode: 'single' | 'list';
        fieldSchema: Array<{
            id: string;
            label: string;
            description?: string | null;
            type: 'text' | 'textarea' | 'number' | 'select' | 'boolean' | 'image';
            required: boolean;
            options: Array<{
                label: string;
                value: string;
            }>;
        }>;
        items: Array<{
            entryKey: string;
            [key: string]: string | number | boolean | null | {
                imageId: string | null;
                imageUrl: string | null;
                imageUrls?: {
                    original: string;
                    small: string;
                    medium: string;
                    large: string;
                    thumbnail: string;
                } | null;
                imageSrcSet?: string | null;
            } | string;
        }>;
    } | null;
};

export type ContentBlockResponse = ContentBlockResponses[keyof ContentBlockResponses];

export type ContentBannerTextData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/content/banner-text';
};

export type ContentBannerTextErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type ContentBannerTextError = ContentBannerTextErrors[keyof ContentBannerTextErrors];

export type ContentBannerTextResponses = {
    /**
     * Successful response
     */
    200: string | null;
};

export type ContentBannerTextResponse = ContentBannerTextResponses[keyof ContentBannerTextResponses];

export type WishlistGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/wishlist';
};

export type WishlistGetErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type WishlistGetError = WishlistGetErrors[keyof WishlistGetErrors];

export type WishlistGetResponses = {
    /**
     * Successful response
     */
    200: Array<{
        id: string;
        storeId: string;
        customerId: string;
        productId: string;
        productVariantId: string | null;
        /**
         * ISO 8601 date-time string. tRPC callers may receive a Date.
         */
        addedAt: string;
        product: {
            id: string;
            name: string;
            slug: string;
            storeId?: string | null;
            primaryImageId?: string | null;
            primaryImageUrl?: string | null;
            primaryImageSrcSet?: string | null;
            description?: string | null;
            status?: 'ACTIVE' | 'DRAFT' | 'ARCHIVED' | null;
            options?: {
                giftCard?: {
                    price: {
                        min: number;
                        max: number;
                        options: Array<number>;
                        customAmountEnabled: boolean;
                    };
                    validityDays: number;
                    terms: string;
                    recipient: {
                        name: boolean;
                        email: boolean;
                        message: boolean;
                    } | null;
                } | null;
            } | null;
            type: 'physical' | 'digital' | 'gift_card';
            /**
             * Base product price in minor currency units.
             */
            price: number;
            stockStatus?: 'IN_STOCK' | 'LOW_STOCK' | 'VERY_LOW_STOCK' | 'OUT_OF_STOCK' | 'NOT_TRACKED';
            stockCount: number;
            trackInventory: boolean;
            customTextFields?: Array<{
                id: string;
                label: string;
                placeholder?: string;
                required?: boolean;
                maxLength?: number;
            }> | null;
            imageIds: Array<string>;
            imageUrls?: Array<string>;
            imageSrcSets?: Array<string>;
            variants: Array<{
                id: string;
                productId: string;
                storeId?: string | null;
                stockCount?: number | null;
                trackInventory?: boolean | null;
                /**
                 * Variant-specific price in minor currency units. When null, use the product price.
                 */
                price?: number | null;
                imageId?: string | null;
                imageUrl?: string | null;
                imageUrlSet?: string | null;
                attributes: Array<{
                    /**
                     * Product option id.
                     */
                    id: string;
                    /**
                     * Product option name, for example Size or Colour.
                     */
                    name: string;
                    value: {
                        /**
                         * Product option value id.
                         */
                        id: string;
                        /**
                         * Selected value for this variant option.
                         */
                        value: string;
                    };
                }>;
            }>;
            sale?: {
                id: string;
                /**
                 * Calculated discount amount in minor currency units.
                 */
                discount: number;
                starts: string | null;
                ends: string | null;
                name: string;
                amount: number | null;
                percentage: number | null;
                active: boolean;
                productIds?: Array<string> | null;
                collectionIds?: Array<string> | null;
            };
        };
        productVariant: {
            id: string;
            productId: string;
            storeId?: string | null;
            stockCount?: number | null;
            trackInventory?: boolean | null;
            /**
             * Variant-specific price in minor currency units. When null, use the product price.
             */
            price?: number | null;
            imageId?: string | null;
            imageUrl?: string | null;
            imageUrlSet?: string | null;
            attributes: Array<{
                /**
                 * Product option id.
                 */
                id: string;
                /**
                 * Product option name, for example Size or Colour.
                 */
                name: string;
                value: {
                    /**
                     * Product option value id.
                     */
                    id: string;
                    /**
                     * Selected value for this variant option.
                     */
                    value: string;
                };
            }>;
        } | null;
    }>;
};

export type WishlistGetResponse = WishlistGetResponses[keyof WishlistGetResponses];

export type WishlistClearData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/wishlist/items';
};

export type WishlistClearErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type WishlistClearError = WishlistClearErrors[keyof WishlistClearErrors];

export type WishlistClearResponses = {
    /**
     * Successful response
     */
    200: Array<{
        id: string;
        storeId: string;
        customerId: string;
        productId: string;
        productVariantId: string | null;
        /**
         * ISO 8601 date-time string. tRPC callers may receive a Date.
         */
        addedAt: string;
        product: {
            id: string;
            name: string;
            slug: string;
            storeId?: string | null;
            primaryImageId?: string | null;
            primaryImageUrl?: string | null;
            primaryImageSrcSet?: string | null;
            description?: string | null;
            status?: 'ACTIVE' | 'DRAFT' | 'ARCHIVED' | null;
            options?: {
                giftCard?: {
                    price: {
                        min: number;
                        max: number;
                        options: Array<number>;
                        customAmountEnabled: boolean;
                    };
                    validityDays: number;
                    terms: string;
                    recipient: {
                        name: boolean;
                        email: boolean;
                        message: boolean;
                    } | null;
                } | null;
            } | null;
            type: 'physical' | 'digital' | 'gift_card';
            /**
             * Base product price in minor currency units.
             */
            price: number;
            stockStatus?: 'IN_STOCK' | 'LOW_STOCK' | 'VERY_LOW_STOCK' | 'OUT_OF_STOCK' | 'NOT_TRACKED';
            stockCount: number;
            trackInventory: boolean;
            customTextFields?: Array<{
                id: string;
                label: string;
                placeholder?: string;
                required?: boolean;
                maxLength?: number;
            }> | null;
            imageIds: Array<string>;
            imageUrls?: Array<string>;
            imageSrcSets?: Array<string>;
            variants: Array<{
                id: string;
                productId: string;
                storeId?: string | null;
                stockCount?: number | null;
                trackInventory?: boolean | null;
                /**
                 * Variant-specific price in minor currency units. When null, use the product price.
                 */
                price?: number | null;
                imageId?: string | null;
                imageUrl?: string | null;
                imageUrlSet?: string | null;
                attributes: Array<{
                    /**
                     * Product option id.
                     */
                    id: string;
                    /**
                     * Product option name, for example Size or Colour.
                     */
                    name: string;
                    value: {
                        /**
                         * Product option value id.
                         */
                        id: string;
                        /**
                         * Selected value for this variant option.
                         */
                        value: string;
                    };
                }>;
            }>;
            sale?: {
                id: string;
                /**
                 * Calculated discount amount in minor currency units.
                 */
                discount: number;
                starts: string | null;
                ends: string | null;
                name: string;
                amount: number | null;
                percentage: number | null;
                active: boolean;
                productIds?: Array<string> | null;
                collectionIds?: Array<string> | null;
            };
        };
        productVariant: {
            id: string;
            productId: string;
            storeId?: string | null;
            stockCount?: number | null;
            trackInventory?: boolean | null;
            /**
             * Variant-specific price in minor currency units. When null, use the product price.
             */
            price?: number | null;
            imageId?: string | null;
            imageUrl?: string | null;
            imageUrlSet?: string | null;
            attributes: Array<{
                /**
                 * Product option id.
                 */
                id: string;
                /**
                 * Product option name, for example Size or Colour.
                 */
                name: string;
                value: {
                    /**
                     * Product option value id.
                     */
                    id: string;
                    /**
                     * Selected value for this variant option.
                     */
                    value: string;
                };
            }>;
        } | null;
    }>;
};

export type WishlistClearResponse = WishlistClearResponses[keyof WishlistClearResponses];

export type WishlistAddData = {
    body: {
        productId: string;
        productVariantId?: string;
    };
    headers: {
        /**
         * Bearer <storefront-public-key>
         */
        authorization: string;
        /**
         * Required for server-side callers when Origin/Referer is unavailable.
         */
        'x-puddle-storefront-host'?: string;
    };
    path?: never;
    query?: never;
    url: '/wishlist/items';
};

export type WishlistAddErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type WishlistAddError = WishlistAddErrors[keyof WishlistAddErrors];

export type WishlistAddResponses = {
    /**
     * Successful response
     */
    200: Array<{
        id: string;
        storeId: string;
        customerId: string;
        productId: string;
        productVariantId: string | null;
        /**
         * ISO 8601 date-time string. tRPC callers may receive a Date.
         */
        addedAt: string;
        product: {
            id: string;
            name: string;
            slug: string;
            storeId?: string | null;
            primaryImageId?: string | null;
            primaryImageUrl?: string | null;
            primaryImageSrcSet?: string | null;
            description?: string | null;
            status?: 'ACTIVE' | 'DRAFT' | 'ARCHIVED' | null;
            options?: {
                giftCard?: {
                    price: {
                        min: number;
                        max: number;
                        options: Array<number>;
                        customAmountEnabled: boolean;
                    };
                    validityDays: number;
                    terms: string;
                    recipient: {
                        name: boolean;
                        email: boolean;
                        message: boolean;
                    } | null;
                } | null;
            } | null;
            type: 'physical' | 'digital' | 'gift_card';
            /**
             * Base product price in minor currency units.
             */
            price: number;
            stockStatus?: 'IN_STOCK' | 'LOW_STOCK' | 'VERY_LOW_STOCK' | 'OUT_OF_STOCK' | 'NOT_TRACKED';
            stockCount: number;
            trackInventory: boolean;
            customTextFields?: Array<{
                id: string;
                label: string;
                placeholder?: string;
                required?: boolean;
                maxLength?: number;
            }> | null;
            imageIds: Array<string>;
            imageUrls?: Array<string>;
            imageSrcSets?: Array<string>;
            variants: Array<{
                id: string;
                productId: string;
                storeId?: string | null;
                stockCount?: number | null;
                trackInventory?: boolean | null;
                /**
                 * Variant-specific price in minor currency units. When null, use the product price.
                 */
                price?: number | null;
                imageId?: string | null;
                imageUrl?: string | null;
                imageUrlSet?: string | null;
                attributes: Array<{
                    /**
                     * Product option id.
                     */
                    id: string;
                    /**
                     * Product option name, for example Size or Colour.
                     */
                    name: string;
                    value: {
                        /**
                         * Product option value id.
                         */
                        id: string;
                        /**
                         * Selected value for this variant option.
                         */
                        value: string;
                    };
                }>;
            }>;
            sale?: {
                id: string;
                /**
                 * Calculated discount amount in minor currency units.
                 */
                discount: number;
                starts: string | null;
                ends: string | null;
                name: string;
                amount: number | null;
                percentage: number | null;
                active: boolean;
                productIds?: Array<string> | null;
                collectionIds?: Array<string> | null;
            };
        };
        productVariant: {
            id: string;
            productId: string;
            storeId?: string | null;
            stockCount?: number | null;
            trackInventory?: boolean | null;
            /**
             * Variant-specific price in minor currency units. When null, use the product price.
             */
            price?: number | null;
            imageId?: string | null;
            imageUrl?: string | null;
            imageUrlSet?: string | null;
            attributes: Array<{
                /**
                 * Product option id.
                 */
                id: string;
                /**
                 * Product option name, for example Size or Colour.
                 */
                name: string;
                value: {
                    /**
                     * Product option value id.
                     */
                    id: string;
                    /**
                     * Selected value for this variant option.
                     */
                    value: string;
                };
            }>;
        } | null;
    }>;
};

export type WishlistAddResponse = WishlistAddResponses[keyof WishlistAddResponses];

export type WishlistRemoveData = {
    body?: never;
    headers: {
        /**
         * Bearer <storefront-public-key>
         */
        authorization: string;
        /**
         * Required for server-side callers when Origin/Referer is unavailable.
         */
        'x-puddle-storefront-host'?: string;
    };
    path: {
        wishlistProductId: string;
    };
    query?: never;
    url: '/wishlist/items/{wishlistProductId}';
};

export type WishlistRemoveErrors = {
    /**
     * The request could not be processed because the input is invalid.
     */
    400: ErrorBadRequest;
    /**
     * The storefront public key is missing or invalid.
     */
    401: ErrorUnauthorized;
    /**
     * The storefront public key, host, or customer session is not allowed to access this resource.
     */
    403: ErrorForbidden;
    /**
     * The requested resource could not be found.
     */
    404: ErrorNotFound;
    /**
     * The request conflicts with the current cart, inventory, or account state.
     */
    409: ErrorConflict;
    /**
     * Too many requests. Retry after a short delay.
     */
    429: ErrorTooManyRequests;
    /**
     * An unexpected server error occurred.
     */
    500: ErrorInternalServerError;
};

export type WishlistRemoveError = WishlistRemoveErrors[keyof WishlistRemoveErrors];

export type WishlistRemoveResponses = {
    /**
     * Successful response
     */
    200: Array<{
        id: string;
        storeId: string;
        customerId: string;
        productId: string;
        productVariantId: string | null;
        /**
         * ISO 8601 date-time string. tRPC callers may receive a Date.
         */
        addedAt: string;
        product: {
            id: string;
            name: string;
            slug: string;
            storeId?: string | null;
            primaryImageId?: string | null;
            primaryImageUrl?: string | null;
            primaryImageSrcSet?: string | null;
            description?: string | null;
            status?: 'ACTIVE' | 'DRAFT' | 'ARCHIVED' | null;
            options?: {
                giftCard?: {
                    price: {
                        min: number;
                        max: number;
                        options: Array<number>;
                        customAmountEnabled: boolean;
                    };
                    validityDays: number;
                    terms: string;
                    recipient: {
                        name: boolean;
                        email: boolean;
                        message: boolean;
                    } | null;
                } | null;
            } | null;
            type: 'physical' | 'digital' | 'gift_card';
            /**
             * Base product price in minor currency units.
             */
            price: number;
            stockStatus?: 'IN_STOCK' | 'LOW_STOCK' | 'VERY_LOW_STOCK' | 'OUT_OF_STOCK' | 'NOT_TRACKED';
            stockCount: number;
            trackInventory: boolean;
            customTextFields?: Array<{
                id: string;
                label: string;
                placeholder?: string;
                required?: boolean;
                maxLength?: number;
            }> | null;
            imageIds: Array<string>;
            imageUrls?: Array<string>;
            imageSrcSets?: Array<string>;
            variants: Array<{
                id: string;
                productId: string;
                storeId?: string | null;
                stockCount?: number | null;
                trackInventory?: boolean | null;
                /**
                 * Variant-specific price in minor currency units. When null, use the product price.
                 */
                price?: number | null;
                imageId?: string | null;
                imageUrl?: string | null;
                imageUrlSet?: string | null;
                attributes: Array<{
                    /**
                     * Product option id.
                     */
                    id: string;
                    /**
                     * Product option name, for example Size or Colour.
                     */
                    name: string;
                    value: {
                        /**
                         * Product option value id.
                         */
                        id: string;
                        /**
                         * Selected value for this variant option.
                         */
                        value: string;
                    };
                }>;
            }>;
            sale?: {
                id: string;
                /**
                 * Calculated discount amount in minor currency units.
                 */
                discount: number;
                starts: string | null;
                ends: string | null;
                name: string;
                amount: number | null;
                percentage: number | null;
                active: boolean;
                productIds?: Array<string> | null;
                collectionIds?: Array<string> | null;
            };
        };
        productVariant: {
            id: string;
            productId: string;
            storeId?: string | null;
            stockCount?: number | null;
            trackInventory?: boolean | null;
            /**
             * Variant-specific price in minor currency units. When null, use the product price.
             */
            price?: number | null;
            imageId?: string | null;
            imageUrl?: string | null;
            imageUrlSet?: string | null;
            attributes: Array<{
                /**
                 * Product option id.
                 */
                id: string;
                /**
                 * Product option name, for example Size or Colour.
                 */
                name: string;
                value: {
                    /**
                     * Product option value id.
                     */
                    id: string;
                    /**
                     * Selected value for this variant option.
                     */
                    value: string;
                };
            }>;
        } | null;
    }>;
};

export type WishlistRemoveResponse = WishlistRemoveResponses[keyof WishlistRemoveResponses];
